/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thuchanh1;

/**
 *
 * @author ubuntu
 */
public class frmDangKyUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmDangKyUser.class.getName());

    /**
     * Creates new form frmDangKyUser
     */
    public frmDangKyUser() {
        initComponents();
        
        // ép hình nền dãn tràn viền phủ kín form
        if (jLabel5.getIcon() != null) {
            java.awt.Image img = ((javax.swing.ImageIcon) jLabel5.getIcon()).getImage();
            java.awt.Image scaledImg = img.getScaledInstance(this.getWidth(), this.getHeight(), java.awt.Image.SCALE_SMOOTH);
            jLabel5.setIcon(new javax.swing.ImageIcon(scaledImg));
            jLabel5.setBounds(0, 0, this.getWidth(), this.getHeight());
        }
        
        // làm trong suốt 3 nut radio
        choread.setOpaque(false);
        chowrite.setOpaque(false);
        chofull.setOpaque(false);
        
        // tạo viền bo góc màu tím pastel xuyệt-tông với con mèo (số 2 là độ dày, true là bo góc)
        java.awt.Color viendep = new java.awt.Color(170, 140, 220);
        javax.swing.border.Border boGoc = javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(viendep, 2, true), // true: BẬT BO TRÒN GÓC
            javax.swing.BorderFactory.createEmptyBorder(5, 12, 5, 12) // Tạo khoảng đệm cách lề trong
        );

        // 2. Gắn viền bo góc cho 3 ô nhập
        txtusername.setBorder(boGoc);
        txtpassword.setBorder(boGoc);
        txtpath.setBorder(boGoc);

        // 3. Hiệu ứng kính mờ trong suốt (số 210 cuối cùng là độ mờ đục: càng nhỏ càng trong suốt)
        txtusername.setBackground(new java.awt.Color(255, 255, 255, 210));
        txtpassword.setBackground(new java.awt.Color(255, 255, 255, 210));
        txtpath.setBackground(new java.awt.Color(255, 255, 255, 210));

        // (Khuyến mãi thêm) Bo nhẹ góc cho 2 nút bấm luôn cho đồng bộ:
        btnRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 100, 200), 2, true));
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 160, 160), 2, true));
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtpath = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        choread = new javax.swing.JRadioButton();
        chowrite = new javax.swing.JRadioButton();
        chofull = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 56, 131, 48));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 110, 365, 38));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 166, 130, 46));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 224, 365, 48));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Path:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 290, 130, 46));
        getContentPane().add(txtpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 342, 365, 50));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Permission:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 410, 130, 46));

        buttonGroup1.add(choread);
        choread.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        choread.setText("Read");
        getContentPane().add(choread, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 462, -1, -1));

        buttonGroup1.add(chowrite);
        chowrite.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        chowrite.setText("Write");
        getContentPane().add(chowrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 462, -1, -1));

        buttonGroup1.add(chofull);
        chofull.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        chofull.setText("Full");
        getContentPane().add(chofull, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 462, -1, -1));

        btnExit.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 555, 191, -1));

        btnRegister.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 509, 365, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/ubuntu/Downloads/moshimoshi05/Bai01/ThucHanh1/images.jpeg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // lay data tu form
        String username = txtusername.getText();
        String password = new String(txtpassword.getPassword());
        String duongdan = txtpath.getText(); // Chỗ này em đặt tên là txtPath, rất chuẩn!

        // check quyen
        int quyen;
        if (choread.isSelected()) {
            quyen = 0;
        } else if (chowrite.isSelected()) {
            quyen = 1;
        } else {
            quyen = 2;
        }

        // day xuong dbaccess xu ly
        DBAccess acc = new DBAccess();
        String sql = "INSERT INTO account VALUES ('" + username + "', '" + password + "', '" + duongdan + "', " + quyen + ")";

        int kq = acc.Update(sql);
        if (kq > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Đăng ký tài khoản thành công!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Đăng ký thất bại! (Trùng username)", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmDangKyUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chofull;
    private javax.swing.JRadioButton choread;
    private javax.swing.JRadioButton chowrite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtpath;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
