/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thuchanh2;

/**
 *
 * @author ADMIN
 */
public class frmDirectory extends javax.swing.JFrame {

    /**
     * Creates new form frmDirectory
     */
    public frmDirectory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcpath = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtpath = new javax.swing.JTextField();
        btnChonDuongDan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtkytu = new javax.swing.JTextField();
        btnlietke = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_file = new javax.swing.JList<>();

        fcpath.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nhập đường dẫn");

        txtpath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnChonDuongDan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChonDuongDan.setText("Chọn đường dẫn");
        btnChonDuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonDuongDanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Lọc bỏ các file không chứa ký tự");

        txtkytu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnlietke.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnlietke.setText("Liệt kê danh sách file");
        btnlietke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlietkeActionPerformed(evt);
            }
        });

        list_file.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(list_file);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)
                        .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnChonDuongDan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtkytu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnlietke)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonDuongDan))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkytu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlietke)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonDuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonDuongDanActionPerformed
        int returnVal = fcpath.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fcpath.getSelectedFile();
            txtpath.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnChonDuongDanActionPerformed

    private void btnlietkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlietkeActionPerformed
        java.io.File dir = new java.io.File(txtpath.getText().trim());
        
        //kiem tra path hop le
        if (!dir.exists() || !dir.isDirectory()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sai path hoac dir khong ton tai!", "Loi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String kytu = txtkytu.getText().trim();
        java.io.File[] dsFile;
        
        // filter theo ky tu neu co nhap
        if (kytu.isEmpty()) dsFile = dir.listFiles();
        else {
            dsFile = dir.listFiles(new java.io.FilenameFilter(){
                @Override
                public boolean accept(java.io.File d, String name) {return name.contains(kytu);}
            });
        }
        
        // display list to JList
        javax.swing.DefaultListModel<String> dm = new javax.swing.DefaultListModel<>();
        if (dsFile != null) {
            for (java.io.File f : dsFile) {dm.addElement(f.getName());}
        }
        list_file.setModel(dm);
    }//GEN-LAST:event_btnlietkeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDirectory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonDuongDan;
    private javax.swing.JButton btnlietke;
    private javax.swing.JFileChooser fcpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_file;
    private javax.swing.JTextField txtkytu;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
