/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thuchanh2;

/**
 *
 * @author ADMIN
 */
public class frmReadWriteFile extends javax.swing.JFrame {

    /**
     * Creates new form frmReadWriteFile
     */
    public frmReadWriteFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNhapChuoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNoiDungFile = new javax.swing.JTextField();
        btVietFileNhiPhan = new javax.swing.JButton();
        btDocFileNhiPhan = new javax.swing.JButton();
        btVietFileVanBan = new javax.swing.JButton();
        btDocFileVanBan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nhập tên tập tin:");

        txtFileName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nhập chuỗi:");

        txtNhapChuoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nội dung file:");

        txtNoiDungFile.setEditable(false);
        txtNoiDungFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btVietFileNhiPhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btVietFileNhiPhan.setText("Ghi File nhị phân");
        btVietFileNhiPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVietFileNhiPhanActionPerformed(evt);
            }
        });

        btDocFileNhiPhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDocFileNhiPhan.setText("Đọc File nhị phân");
        btDocFileNhiPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocFileNhiPhanActionPerformed(evt);
            }
        });

        btVietFileVanBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btVietFileVanBan.setText("Ghi File văn bản");
        btVietFileVanBan.setActionCommand("Ghi File văn bản");
        btVietFileVanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVietFileVanBanActionPerformed(evt);
            }
        });

        btDocFileVanBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDocFileVanBan.setText("Đọc File văn bản");
        btDocFileVanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocFileVanBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNoiDungFile, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNhapChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btVietFileVanBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btVietFileNhiPhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDocFileNhiPhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDocFileVanBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNhapChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiDungFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVietFileNhiPhan)
                    .addComponent(btDocFileNhiPhan))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVietFileVanBan)
                    .addComponent(btDocFileVanBan))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVietFileNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVietFileNhiPhanActionPerformed
        byte a[] = new byte[20];
        char s[] =txtNhapChuoi.getText().toCharArray();
        for (int i=0; i<s.length && i<a.length; ++i) {a[i] = (byte)s[i];}
        try {
            java.io.File file = new java.io.File(txtFileName.getText());
            java.io.FileOutputStream fo = new java.io.FileOutputStream(file);
            fo.write(a);
            fo.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Ghi file nhi phan thanh cong!");
        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btVietFileNhiPhanActionPerformed

    private void btDocFileNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocFileNhiPhanActionPerformed
        try {
            java.io.File file = new java.io.File(txtFileName.getText());
            java.io.FileInputStream fi = new java.io.FileInputStream(file);
            byte a[] = new byte[fi.available()];
            fi.read(a);
            fi.close();
            txtNoiDungFile.setText(new String(a));
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "Loi doc file: " + e.getMessage());
        }
    }//GEN-LAST:event_btDocFileNhiPhanActionPerformed

    private void btVietFileVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVietFileVanBanActionPerformed
        try {
            java.io.FileWriter fw = new java.io.FileWriter(new java.io.File(txtFileName.getText()));
            fw.write(txtNhapChuoi.getText());
            fw.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Ghi file van ban thanh cong!");
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btVietFileVanBanActionPerformed

    private void btDocFileVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocFileVanBanActionPerformed
        try {
            java.io.FileReader fr = new java.io.FileReader(new java.io.File(txtFileName.getText()));
            StringBuilder sb = new StringBuilder();
            char ca[] = new char[5];
            int len;
            while((len = fr.read(ca)) != -1) {sb.append(ca, 0, len);}
            fr.close();
            txtNoiDungFile.setText(sb.toString());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Loi doc file: " + e.getMessage());
        }
    }//GEN-LAST:event_btDocFileVanBanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReadWriteFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDocFileNhiPhan;
    private javax.swing.JButton btDocFileVanBan;
    private javax.swing.JButton btVietFileNhiPhan;
    private javax.swing.JButton btVietFileVanBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtNhapChuoi;
    private javax.swing.JTextField txtNoiDungFile;
    // End of variables declaration//GEN-END:variables
}
